# Variables to inject into Java variables
ebayTokenUrl: ${EBAY_TOKEN_URL:https://api.ebay.com/identity/v1/oauth2/token}
ebayItemSummaryApiUrl: ${EBAY_BROWSE_API_ITEM_SUMMARY_URL:https://api.ebay.com/buy/browse/v1/item_summary/search}
ebayGetItemApiUrl: ${EBAY_BROWSE_API_GET_ITEM_URL:https://api.ebay.com/buy/browse/v1/item}
principalRoleName: ${PRINCIPAL_ROLE_NAME:administrator}

eureka:
    client:
        service-url:
            default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
logging:
    level:
        root: warn
server:
    port: ${SERVER_PORT:8000}
spring:
    application:
        name: product-retriever-service
    cloud:
        loadbalancer:
            cache:
                enabled: true
            enabled: true
    devtools:
        livereload:
            enabled: true
            port: ${LIVERELOAD_PORT:35730}
    main:
        banner-mode: 'off'
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${OAUTH2_PROVIDER_ISSUER_URL}
                opaquetoken:
                    client-id: ${OAUTH2_PROVIDER_CLIENT_ID}
                    client-secret: ${OAUTH2_PROVIDER_CLIENT_SECRET}
                    introspection-uri: ${OAUTH2_PROVIDER_INTROSPECTION_URL}
    datasource:
        driver-class-name: org.postgresql.Driver
        password: ${DATASOURCE_PASSWORD}
        url: jdbc:postgresql://${DATASOURCE_HOST}/${DATASOURCE_NAME}
        username: ${DATASOURCE_USERNAME}
    jpa:
        open-in-view: true
    flyway:
        enabled: true
        baseline-on-migrate: true
        validate-on-migrate: true
